### ISSUE TITLE
List of jobs are shown when refreshing job view

### ISSUE THREAD

**Issue by sduenas** [Bitergia/raistlin#14]
There is a visualization error when refreshing a job view. When it is refreshed, the full list of jobs is shown under the **logs box**. 

See the screencast with this behaviour:

![raistlin_error_job_refresh](https://user-images.githubusercontent.com/833352/67380318-6af14700-f58a-11e9-9600-71ed8d8284d3.gif)

**Comment by dlumbrer** [comment]
I submitted a PR with the fix (#17 ), I realized that the problem appeared when the back/forward buttons of the browser were clicked, I fix that problem as well, this is how it works now:

![Peek 2019-10-23 13-19](https://user-images.githubusercontent.com/9249232/67388013-36848780-f598-11e9-8163-080a99d41e2b.gif)

Please @sduenas , check the PR when you can
