### ISSUE TITLE
Show job number when refering to jobs

### ISSUE THREAD

**Issue by sduenas** [Bitergia/raistlin#16]
Recently, we introduced in **Arthur** a human readable identifier for jobs (see chaoss/grimoirelab-kingarthur#96). These identifier are not unique but allow to identify jobs faster. These identifiers are just plain integers so we can introduce references in the app like `Job #1` and so on. These references are easier to understand than long hashes.

The hashes could be kept and referenced but their presence should be reduced.

**Comment by dlumbrer** [comment]
A PR with the functionality has been made: #18 

It is not ready to test until https://github.com/chaoss/grimoirelab-kingarthur/issues/104 has been solved/done
