### ISSUE TITLE
Cancel/delete tasks in Arthur

### ISSUE THREAD

**Issue by sduenas** [Bitergia/raistlin#19]
Athur server provides a method to remove and cancel a task at the same time. We should have a way in the user interface to call this method.

**Comment by dlumbrer** [comment]
A PR has been created (#20) with the corresponding feature, the next GIF shows the behavior:

![Peek 2019-11-12 15-35](https://user-images.githubusercontent.com/9249232/68680690-67862580-0562-11ea-858b-429e3272d54c.gif)

Please, @sduenas , check it when you can

**Comment by dlumbrer** [comment]
> PR updated, here is how it looks like with a cross:
> 
>

Updated again, with this new aspect:

![Screenshot from 2019-11-13 12-49-03](https://user-images.githubusercontent.com/9249232/68761269-074fbc00-0614-11ea-9c86-350a011d3336.png)



Please, @sduenas , check it again when you have time, thanks!

_Originally posted by @dlumbrer in https://github.com/Bitergia/raistlin/pull/20#issuecomment-553369854_
