### ISSUE TITLE
Show the result of a completed/failed job

### ISSUE THREAD

**Issue by sduenas** [Bitergia/raistlin#21]
The current job view shows only the logs generated when a job is running. It should also show the result of a job which includes the number of items generated, skipped or ignored, the uuids of the items and so on.

**Comment by dlumbrer** [comment]
A PR has been submitted #26 , please @sduenas check it when you have time.

This is the result in the UI:

![Peek 2019-11-25 12-21](https://user-images.githubusercontent.com/9249232/69536516-63083680-0f7e-11ea-95bf-81e76a050240.gif)
