### ISSUE TITLE
Refresh job status

### ISSUE THREAD

**Issue by sduenas** [Bitergia/raistlin#25]
Jobs list view and jobs view doesn't refresh the status of each job. The user has to to it manually.
The goal of this issue is to add an autorefresh so the views are constantly updated to show the current status.

**Comment by dlumbrer** [comment]
The PR submitted allows to refresh all the data of the Job, so it refreshes both status and logs. Therefore, the PR submitted #30 solves this issue as solves issue #23  as well.

Please, @sduenas , check it when you have time.
